server:
  servlet:
    context-path: /demo/
  port: 9000

management:
  port: 9001
  address: 127.0.0.1

spring:
    redis:
      database: 0
      host: 192.168.0.105
      port: 6379
      password: foobared
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 100s
    maxplus1:
        shiro:
            tokenKey: uuusid
            loginUrl: /api/sys/login
            filterChainDefinitionMap:
                "/static/**": "anon"
                "/api/sys/ssoLogin": "anon"
                "/api/sys/login": "anon"
                "/api/sys/testRedis": "anon"
                "/api/**": "perms"
                "/**": "authc"
                "/api/sys/logout": "logout"
            globalSessionTimeout: 180000000 # 3,600,000 milliseconds = 1 hour
            sessionValidationInterval: 360000 # 会话有效校验扫描间隔
            redisCacheEnabled: true # 开启分布式session 需要引入Redis的相关配置，spring-data-redis
            testMode: false # 开启测试模式，测试模式下所有url的访问权限都是anon
            mockUser: # 测试模式模拟的用户
                userId: 'MOCK_USER0'
                userName: 'mock_yonghu0'
                deptId: 'MOCK_DEPT0'
                deptName: '模拟部门0'
                realName: '模拟用户0'
                status: '正常'
                password: 'MOCK_PASS0'
