server:
  servlet:
    context-path: /demo/
  port: 9000

management:
  port: 9001
  address: 127.0.0.1

spring:
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    maxplus1:
        shiro:
            tokenKey: uuusid
            loginUrl: /api/sys/login
            filterChain: | # 注意所有perms的权限都需要通过@RequirePermissions来实现，建议不要配置perms（动态URL问题）。PS:yaml配置map的key含有/时，无法识别/。
                /static/**=anon
                /api/sys/ssoLogin=anon
                /api/sys/login=anon
                /api/sys/testRedis=anon
                /api/**=authc
                /**=authc
                /api/sys/logout=logout
            globalSessionTimeout: 180000000 # 3,600,000 milliseconds = 1 hour
            sessionValidationInterval: 360000 # 会话有效校验扫描间隔
            redisCacheEnabled: false # 开启分布式session 需要引入Redis的相关配置，spring-data-redis
            testMode: false # 开启测试模式，测试模式下所有url的访问权限都是anon
            mockUser: # 测试模式模拟的用户
                userId: 'MOCK_USER0'
                userName: 'mock_yonghu0'
                deptId: 'MOCK_DEPT0'
                deptName: '模拟部门0'
                realName: '模拟用户0'
                status: '正常'
                password: 'MOCK_PASS0'
